apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-esload
  name: giggso-esload
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: giggso-esload

