apiVersion: v1
kind: Service
metadata:
  labels:
    service: workflow
  name: workflow
spec:
  type: ClusterIP
  ports:
  - name: "8202"
    port: 8202
    targetPort: 8202
  selector:
    service: workflow

