apiVersion: v1
kind: Service
metadata:
  labels:
    service: test
  name: test
spec:
  type: ClusterIP
  ports:
  - name: "8204"
    port: 8204 
    targetPort: 8204
  selector:
    service: test
