apiVersion: v1
kind: Service
metadata:
  labels:
    service: ask-giggso
  name: ask-giggso
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8204"
    port: 8204
    targetPort: 8204
  - name: "8202"
    port: 8202
    targetPort: 8202
  selector:
    service: ask-giggso

