apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: ask-giggso
  name: ask-giggso
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: ask-giggso
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: ask-giggso
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - image: giggsodocker/ask-giggso
        name: ask-giggso
        resources:
          requests:
            cpu: "200m"
            memory: "1Gi"
          limits:
            cpu: "450m"
            memory: "6Gi"
        ports:
        - containerPort: 8080
        - containerPort: 8202
        - containerPort: 8204
      restartPolicy: Always
      nodeSelector:
        dedicated_label: ml
      tolerations:
        - key: "dedicated_label"
          operator: "Equal"
          value: "ml"
          effect: "NoSchedule"

