apiVersion: v1
kind: Service
metadata:
  labels:
    service: ml-scale-ml-service-api
  name: ml-service-api
spec:
  type: ClusterIP
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8080
  selector:
    service: ml-scale-ml-service-api

