apiVersion: v1
kind: Service
metadata:
  labels:
    service: keycloak
  name: keycloak
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9002"
    port: 9002
    targetPort: 8443
  selector:
    service: keycloak
