kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: kafka
        #image: wurstmeister/kafka
        image: giggsodocker/giggso-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://10.4.0.6:30162,OUTSIDE://ggdev.giggso.com:30162"
        - name: KAFKA_LISTENERS
          value: "INSIDE://:9092,OUTSIDE://:30162"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: "gglograwdata:1:1,gg-noncore-errors:1:1,gg-capacity-alerts:1:1,my-topic:1:1,gglogs:1:1,ggerrorprocessed:1:1,ggprocessess:1:1,ggerrors:1:1,ggrulematches:1:1,ggruleprocessed:1:1,gganomalies:1:1,gg-noncore-data:1:1" #test:1:1
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"

