apiVersion: v1
kind: Service
metadata:
  labels:
    service: jobapi
  name: jobapi
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8082
    targetPort: 8080
  selector:
    service: jobapi

