apiVersion: apps/v1
kind: Deployment
metadata:
  name: loganomaly-jobchecker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: loganomaly-jobchecker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: loganomaly-jobchecker
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - env:
         - name: JOB_INTERVAL
           value: "1"
         - name: INDEX
           value: ggjobsanomaly
         - name: PULSAR_URL
           value: pulsar://pulsar:6650
         - name: ELASTICSEARCH_URL
           value: http://elasticsearch:9200
         - name: JOB_CREATION_API
           value: http://loganomaly-jobapi:8083
         - name: ES_USER
           value: elastic
         - name: ES_PASS
           value: changeme
         - name: TRINO_HOST
           value: trino
         - name: TRINO_USER
           value: username
         - name: TRINO_PORT
           value: "8080"
         - name: TRINO_JOBS_CATALOG
           value: elasticsearch
         - name: TRINO_SCHEMA
           value: default
        image: giggsodocker/loganomaly_jobchecker
        imagePullPolicy: "Always"
        name: loganomaly-jobchecker
        resources:
          requests:
            cpu: "300m"
            memory: "400Mi"
          limits:
            cpu: "350m"
            memory: "500Mi"
      restartPolicy: Always
      nodeSelector:
        dedicated_label: ml
      tolerations:
        - key: "dedicated_label"
          operator: "Equal"
          value: "ml"
          effect: "NoSchedule"
      serviceAccountName: ""
      
