apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gglogsrollover
spec:
  schedule: "* 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: docker-secret
          containers:
          - name: gglogsrollover
            image: ubuntu:18.04
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |- 
              (apt update -y) && (apt install curl -y) && (./run.sh)
            volumeMounts:
            - mountPath: ./run.sh
              subPath: run.sh
              name: es-rollover-cfg
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: es-rollover-cfg
            configMap:
              name: es-rollover-cfg
              defaultMode: 0777

