apiVersion: v1
kind: Service
metadata:
  labels:
    service: error-detection
  name: error-detection
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: error-detection

