apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: angular
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      service: angular
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: angular
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: angular
        image: giggsodocker/angular-k8-uat
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        - containerPort: 411
        resources: {}        
        volumeMounts:
        - mountPath: /usr/share/nginx/html/env.js
          subPath: env.js
          name: env-config
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: env-config
        configMap:
          name: env-config
          defaultMode: 0777

