apiVersion: v1
data:
  giggsoaccess.properties: 
  apiVersion: v1
data:
  rulemicroservice.properties: |
    ##########################################################################################################
    ###### Elastic Search Source Configuration ###############################################################
    SOURCE_SCHEMA=http
    SOURCE_HOST=dev.giggso.com
    SOURCE_PORT=7300
    SOURCE_REST_PORT=7201
    SOURCE_HOST_USERNAME=elastic
    SOURCE_HOST_PASSWORD=changeme
    SOURCE_HOST_CONNECTION_TIMEOUT=100
    CLUSTER_NAME=docker-cluster
    

kind: ConfigMap
metadata:
  name: azupload-config

