apiVersion: v1
data:
  core-site.xml: "<configuration>\r\n  <property>\r\n\t<name>fs.azure.account.key.storageaccountname.blob.core.windows.net</name>\r\n\t
    \     <value>storageaccesskey</value>\r\n
    \   </property>\r\n </configuration>\r\n"
  metastore-site.xml: "<configuration>\n<property>\n\t<name>metastore.task.threads.always</name>\n\t<value>org.apache.hadoop.hive.metastore.events.EventCleanerTask</value>\n</property>\n<property>\n\t<name>metastore.expression.proxy</name>\n\t<value>org.apache.hadoop.hive.metastore.DefaultPartitionExpressionProxy</value>\n</property>\n<property>\n\t<name>javax.jdo.option.ConnectionDriverName</name>\n\t<value>com.mysql.jdbc.Driver</value>\n</property>\n<property>\n\t<name>javax.jdo.option.ConnectionURL</name>\n\t<value>jdbc:mysql://giggso-mariadb:3306/metastore_db</value>\n</property>\n<property>\n\t<name>javax.jdo.option.ConnectionUserName</name>\n\t<value>root</value>\n</property>\n<property>\n\t<name>javax.jdo.option.ConnectionPassword</name>\n\t<value>root</value>\n</property>\n<property>\n\t<name>metastore.thrift.port</name>\n\t<value>9083</value>\n</property>\n</configuration>\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: metastore-cfg
