apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-webpush
  name: giggso-webpush
spec:
  type: NodePort
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: giggso-webpush

