apiVersion: v1
data:
  rulemicroservice.properties: |
    ##########################################################################################################
    ###### Elastic Search Source Configuration ###############################################################
    SOURCE_SCHEMA=http
    SOURCE_HOST=elasticsearch
    SOURCE_PORT=9300
    SOURCE_REST_PORT=9200
    SOURCE_HOST_USERNAME=elastic
    SOURCE_HOST_PASSWORD=changeme
    SOURCE_HOST_CONNECTION_TIMEOUT=100
    CLUSTER_NAME=docker-cluster

    ##########################################################################################################
    ###### Rest Template Configuration #######################################################################

    GIGGSO_BASE_URL=http://127.0.0.1:8080/giggzo-0.0.1-SNAPSHOT/rest/
    RULE_URL=rules/v2/processRule
    ERROR_ACTION_RULE_ID=5134

    ##########################################################################################################
    ###### Pulsar Configuration ##############################################################################

    PULSAR_SERVICE_URL=pulsar://pulsar:6650
    #PULSAR_SERVICE_URL=pulsar://127.0.0.1:6650
    PULSAR_GGLOGS_RULE_TOPIC=process_gglogs_rule_topic

    ##########################################################################################################
    ###### Spring Boot Configuration ##############################################################################

    SERVER_PORT=8123

    ########################################################################################################
    #######################################
    ########## Trino Config ###############
    TRINO_JDBC_DRIVER=io.trino.jdbc.TrinoDriver
      #jdbc:trino://example.net:8080/topic/schema?user=test&password=****&SSL=true
    TRINO_JDBC_BASE_URL=jdbc:trino://trino:8080/kafka/default?user=test
    #topic to fetch the logs from the kafka
    TRINO_KAFKA_TOPIC_GGLOGS=gglogs
    #######################################

    #######################################
    ########## Kafka Config ###############
    KAFKA_BASE_URL=kafka-cluster
    KAFKA_PORT=9092
    #topic to produce matched rules
    KAFKA_TOPIC_MATCHED_RULES=ggrulematches
    #topic to produce unmatched rules
    KAFKA_TOPIC_UNMATCHED_RULES=ggruleprocessed
    #######################################
  
kind: ConfigMap
metadata:
  name: ruleengine-config

