apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-aiml-sme
  name: giggso-aiml-sme
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 5000
    targetPort: 5000
  selector:
    service: giggso-aiml-sme

