apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: giggso-aiml-sme
  name: giggso-aiml-sme
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: giggso-aiml-sme
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: giggso-aiml-sme
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: 'http://elasticsearch:9200'
        - name: NEO4J_URL
          value: 'bolt://neo4j:7687'
        image: giggsodocker/giggso-aiml-sme
        name: giggso-aiml-sme
        resources:
          requests:
            cpu: "200m"
            memory: "1Gi"
          limits:
            cpu: "450m"
            memory: "6Gi"
        ports:
        - containerPort: 5000
      restartPolicy: Always
      nodeSelector:
        dedicated_label: ml
      tolerations:
        - key: "dedicated_label"
          operator: "Equal"
          value: "ml"
          effect: "NoSchedule"

