apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-enrichdata
  name: giggso-enrichdata
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: giggso-enrichdata

