apiVersion: v1
kind: Service
metadata:
  labels:
    service: gg-recommendations
  name: gg-recommendations
spec:
  type: ClusterIP
  ports:
  - name: "8202"
    port: 8202 
    targetPort: 8202
  selector:
    service: gg-recommendations

