apiVersion: v1
kind: Service
metadata:
  labels:
    service: loganomaly-jobapi
  name: loganomaly-jobapi
spec:
  type: ClusterIP
  ports:
  - name: "8080"
    port: 8083
    targetPort: 8080
  selector:
    service: loganomaly-jobapi

