apiVersion: v1
kind: Service
metadata:
  labels:
    service: logstash
  name: logstash
  namespace: nginx-ingress
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  - name: 5000-udp
    port: 5000
    protocol: UDP
    targetPort: 5000
  - name: "5044"
    port: 5044
    targetPort: 5044
  selector:
    service: logstash
