apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-logingestion
  name: giggso-logingestion
spec:
  type: ClusterIP
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service: giggso-logingestion

