apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: giggso-logingestion
  name: giggso-logingestion
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: giggso-logingestion
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: giggso-logingestion
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - env:
         - name: LOG_ENDPOINT
           value: domain-name:5044
         - name: METRIC_ENDPOINT
           value: domainname:30920
         - name: PACKET_ENDPOINT
           value: domainname:30920  
           #value: http://ggdev.giggso.com:30920
        image: giggsodocker/giggso-log-ingestion-uat
        imagePullPolicy: "Always"
        name: capacityjob
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
      restartPolicy: Always
      serviceAccountName: ""
      nodeSelector:
        dedicated_label: ml
      tolerations:
        - key: "dedicated_label"
          operator: "Equal"
          value: "ml"
          effect: "NoSchedule"
      serviceAccountName: ""
