kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 2
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: kafka
        #image: wurstmeister/kafka
        image: giggsodocker/giggso-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30162"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 10.4.0.6 # 192.168.1.240
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_CREATE_TOPICS
          value: test:1:1
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
