apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: correlated-events
  name: correlated-events
spec:
  replicas: 1 
  selector:
    matchLabels:
      service: correlated-events
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: correlated-events
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: 'http://elasticsearch:9200'
        - name: ES_USER
          value: elastic
        - name: ES_PASS
          value: changeme
        - name: TRINO_URL
          value: trino
        - name: TRINO_USER
          value: username
        - name: TRINO_PORT
          value: "8080"
        - name: TRINO_ELASTIC_CATALOG
          value: elasticsearch
        - name: TRINO_ELASTIC_SCHEMA
          value: default          
        - name: TRINO_AZURE_SCHEMA
          value: default
        - name: TRINO_AZURE_CATALOG
          value: hive
        - name: TRINO_KAFKA_SCHEMA
          value: default
        - name: TRINO_KAFKA_CATALOG
          value: kafka

        image: giggsodocker/giggso-aiml-correlated
        name: correlated-events
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "250m"
            memory: "2Gi"
        ports:
        - containerPort: 8203
          #- containerPort: 2222
      restartPolicy: Always
      nodeSelector:
        dedicated_label: ml
      tolerations:
        - key: "dedicated_label"
          operator: "Equal"
          value: "ml"
          effect: "NoSchedule"

