apiVersion: v1
kind: Service
metadata:
  labels:
    service: giggso-aiml-rca
  name: giggso-aiml-rca
spec:
  type: ClusterIP
  ports:
  - name: "8202"
    port: 8202 
    targetPort: 8202
  selector:
    service: giggso-aiml-rca

