apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pulsar
  name: pulsar
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pulsar
  template:
    metadata:
      labels:
        service: pulsar
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - |-
          (bin/apply-config-from-env.py conf/standalone.conf) &&
          (bin/pulsar sql-worker run > /dev/null 2>&1 &) &&
          (bin/pulsar standalone)
        image: apachepulsar/pulsar:2.3.1
        imagePullPolicy: ""
        name: pulsar
        ports:
        - containerPort: 6650
        - containerPort: 8080
        - containerPort: 8000
        resources: {}
      restartPolicy: Always

