apiVersion: v1
kind: Service
metadata:
  labels:
    service: pulsar
  name: pulsar
spec:
  ports:
  - name: "6650"
    port: 6650
    targetPort: 6650
  - name: "8010"
    port: 8010
    targetPort: 8080
  - name: "8002"
    port: 8002
    targetPort: 8000
  selector:
    service: pulsar
