apiVersion: v1
data:
  entrypoint.sh: |
    #!/bin/sh
    /opt/rh/rh-python36/root/usr/bin/bert-serving-start -model_dir /root/pyjavatest/uncased_L-12_H-768_A-12/ -num_worker=1  &
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: entrypoint
