apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    service: web-log
  name: web-log
spec:
  storageClassName: "nfs"
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
status: {}
