apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
     service: web
#    io.kompose.app: web
  name: web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "9003"
    port: 9003
    targetPort: 8443
  - name: "9993"
    port: 9993
    targetPort: 9993
  - name: "9990"
    port: 9990
    targetPort: 9990
  selector:
    service: web
    app: web
status:
  loadBalancer: {}
